# Generated by Django 6.0.1 on 2026-02-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raf_start', '0003_alter_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Platform ID')),
                ('name', models.CharField(max_length=100, verbose_name='Platform Name')),
                ('delivery_type', models.CharField(choices=[('Subscription Video on Demand', 'Subscription Video on Demand'), ('Live TV Streaming', 'Live TV Streaming'), ('Ad Free Streaming', 'Ad Free Streaming')], default='Subscription Video on Demand', max_length=100, verbose_name='Delivery Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='flick',
            name='availability',
        ),
        migrations.AddField(
            model_name='flick',
            name='status',
            field=models.CharField(choices=[('Watched', 'Watched'), ('Watching', 'Watching'), ('Watch', 'Watch')], default='Watch', max_length=20),
        ),
        migrations.RemoveField(
            model_name='flick',
            name='genre',
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Availability ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('flick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raf_start.flick', verbose_name='Flick')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raf_start.platform', verbose_name='Platform')),
            ],
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.AddField(
            model_name='flick',
            name='genre',
            field=models.ManyToManyField(to='raf_start.genre', verbose_name='Genre'),
        ),
    ]
