# Generated by Django 6.0.1 on 2026-02-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raf_start', '0006_flick_duration_platform_areas_served_platform_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, default='platform_logos/default.png', null=True, upload_to='platform_logos/', verbose_name='Platform Logo'),
        ),
    ]
