# Generated by Django 6.0.1 on 2026-02-15 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Genre ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Flick',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Flick ID')),
                ('cover_image', models.ImageField(default='covers/default.jpg', upload_to='covers/', verbose_name='Cover Image')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('director', models.CharField(default='Unknown', max_length=100, verbose_name='Director')),
                ('year', models.IntegerField(default=2000, verbose_name='Year')),
                ('rating', models.FloatField(default=0.0, verbose_name='Rating')),
                ('synopsis', models.TextField(default='No synopsis available.', verbose_name='Synopsis')),
                ('availability', models.BooleanField(default=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf_start.genre', verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Rental ID')),
                ('rental_date', models.DateField(auto_now_add=True, verbose_name='Rental Date')),
                ('return_date', models.DateField(blank=False, null=False, verbose_name='Return Date')),
                ('flick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf_start.flick', verbose_name='Flick')),
            ],
        ),
    ]
