# Generated by Django 6.0.2 on 2026-03-11 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saf_start', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flix',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='flix',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.AddField(
            model_name='flix',
            name='duration',
            field=models.IntegerField(default=120, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='flix',
            name='genres',
            field=models.ManyToManyField(to='saf_start.genre'),
        ),
        migrations.AddField(
            model_name='flix',
            name='status',
            field=models.CharField(choices=[('Watched', 'Watched'), ('Watching', 'Watching'), ('Watch', 'Watch')], default='Watch', max_length=20),
        ),
        migrations.AddField(
            model_name='flix',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flix',
            name='cover_image',
            field=models.ImageField(blank=True, default='covers/default.png', null=True, upload_to='covers/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='flix',
            name='director',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='flix',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='flix',
            name='synopsis',
            field=models.TextField(blank=True, default='No synopsis available.', null=True, verbose_name='Synopsis'),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Platform ID')),
                ('name', models.CharField(max_length=100, verbose_name='Platform Name')),
                ('logo', models.ImageField(blank=True, default='platform_logos/default.png', null=True, upload_to='platform_logos/', verbose_name='Platform Logo')),
                ('parent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent Company')),
                ('areas_served', models.CharField(blank=True, max_length=200, null=True, verbose_name='Areas Served')),
                ('delivery_type', models.CharField(choices=[('Subscription Video on Demand', 'Subscription Video on Demand'), ('Live TV Streaming', 'Live TV Streaming'), ('Ad Free Streaming', 'Ad Free Streaming')], default='Subscription Video on Demand', max_length=100, verbose_name='Delivery Type')),
                ('url', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='No description yet.', null=True, verbose_name='Description')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Availability ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('flix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf_start.flix', verbose_name='Flix')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saf_start.platform', verbose_name='Platform')),
            ],
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
