# Generated by Django 6.0.1 on 2026-02-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saf_start', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flick',
            name='cover_image',
            field=models.ImageField(blank=True, default='covers/default.jpg', null=True, upload_to='covers/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='flick',
            name='director',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='flick',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='flick',
            name='synopsis',
            field=models.TextField(blank=True, default='No synopsis available.', null=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Description'),
        ),
    ]
