# Generated by Django 6.0.1 on 2026-02-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saf_start', '0002_alter_flick_cover_image_alter_flick_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
    ]
