# Generated by Django 6.0.1 on 2026-02-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saf_start', '0005_flick_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flick',
            name='duration',
            field=models.IntegerField(default=120, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='platform',
            name='areas_served',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Areas Served'),
        ),
        migrations.AddField(
            model_name='platform',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent Company'),
        ),
    ]
