# Generated by Django 6.0.1 on 2026-02-16 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saf_start', '0007_platform_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flick',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flick',
            name='genres',
            field=models.ManyToManyField(to='saf_start.genre'),
        ),
        migrations.AddField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, default='No description yet.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='platform',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='platform',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
