# Generated by Django 6.0.2 on 2026-02-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saf_start', '0009_alter_flick_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flick',
            name='cover_image',
            field=models.ImageField(blank=True, default='covers/default.png', null=True, upload_to='covers/', verbose_name='Cover Image'),
        ),
    ]
